// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: serve.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HandleMessageRequest) Reset() {
	*x = HandleMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleMessageRequest) ProtoMessage() {}

func (x *HandleMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleMessageRequest.ProtoReflect.Descriptor instead.
func (*HandleMessageRequest) Descriptor() ([]byte, []int) {
	return file_serve_proto_rawDescGZIP(), []int{0}
}

func (x *HandleMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubMessages map[string]*SubMessage `protobuf:"bytes,1,rep,name=SubMessages,proto3" json:"SubMessages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serve_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_serve_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_serve_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetSubMessages() map[string]*SubMessage {
	if x != nil {
		return x.SubMessages
	}
	return nil
}

type SubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*SubMessage_NValue
	//	*SubMessage_FValue
	//	*SubMessage_SValue
	Value isSubMessage_Value `protobuf_oneof:"Value"`
}

func (x *SubMessage) Reset() {
	*x = SubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serve_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMessage) ProtoMessage() {}

func (x *SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_serve_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMessage.ProtoReflect.Descriptor instead.
func (*SubMessage) Descriptor() ([]byte, []int) {
	return file_serve_proto_rawDescGZIP(), []int{2}
}

func (m *SubMessage) GetValue() isSubMessage_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *SubMessage) GetNValue() int32 {
	if x, ok := x.GetValue().(*SubMessage_NValue); ok {
		return x.NValue
	}
	return 0
}

func (x *SubMessage) GetFValue() float32 {
	if x, ok := x.GetValue().(*SubMessage_FValue); ok {
		return x.FValue
	}
	return 0
}

func (x *SubMessage) GetSValue() string {
	if x, ok := x.GetValue().(*SubMessage_SValue); ok {
		return x.SValue
	}
	return ""
}

type isSubMessage_Value interface {
	isSubMessage_Value()
}

type SubMessage_NValue struct {
	NValue int32 `protobuf:"varint,1,opt,name=nValue,proto3,oneof"`
}

type SubMessage_FValue struct {
	FValue float32 `protobuf:"fixed32,2,opt,name=fValue,proto3,oneof"`
}

type SubMessage_SValue struct {
	SValue string `protobuf:"bytes,3,opt,name=sValue,proto3,oneof"`
}

func (*SubMessage_NValue) isSubMessage_Value() {}

func (*SubMessage_FValue) isSubMessage_Value() {}

func (*SubMessage_SValue) isSubMessage_Value() {}

type HandleMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*HandleMessageResponse_NValue
	//	*HandleMessageResponse_FValue
	//	*HandleMessageResponse_SValue
	Value isHandleMessageResponse_Value `protobuf_oneof:"Value"`
}

func (x *HandleMessageResponse) Reset() {
	*x = HandleMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serve_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleMessageResponse) ProtoMessage() {}

func (x *HandleMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serve_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleMessageResponse.ProtoReflect.Descriptor instead.
func (*HandleMessageResponse) Descriptor() ([]byte, []int) {
	return file_serve_proto_rawDescGZIP(), []int{3}
}

func (m *HandleMessageResponse) GetValue() isHandleMessageResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *HandleMessageResponse) GetNValue() int32 {
	if x, ok := x.GetValue().(*HandleMessageResponse_NValue); ok {
		return x.NValue
	}
	return 0
}

func (x *HandleMessageResponse) GetFValue() float32 {
	if x, ok := x.GetValue().(*HandleMessageResponse_FValue); ok {
		return x.FValue
	}
	return 0
}

func (x *HandleMessageResponse) GetSValue() string {
	if x, ok := x.GetValue().(*HandleMessageResponse_SValue); ok {
		return x.SValue
	}
	return ""
}

type isHandleMessageResponse_Value interface {
	isHandleMessageResponse_Value()
}

type HandleMessageResponse_NValue struct {
	NValue int32 `protobuf:"varint,1,opt,name=nValue,proto3,oneof"`
}

type HandleMessageResponse_FValue struct {
	FValue float32 `protobuf:"fixed32,2,opt,name=fValue,proto3,oneof"`
}

type HandleMessageResponse_SValue struct {
	SValue string `protobuf:"bytes,3,opt,name=sValue,proto3,oneof"`
}

func (*HandleMessageResponse_NValue) isHandleMessageResponse_Value() {}

func (*HandleMessageResponse_FValue) isHandleMessageResponse_Value() {}

func (*HandleMessageResponse_SValue) isHandleMessageResponse_Value() {}

var File_serve_proto protoreflect.FileDescriptor

var file_serve_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x4e,
	0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x51, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e,
	0x52, 0x50, 0x43, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x61, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x37, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x4e, 0x57, 0x4e,
	0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x63, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x18, 0x0a, 0x06, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x00, 0x52, 0x06, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6e, 0x0a,
	0x15, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x18, 0x0a, 0x06, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x00, 0x52, 0x06, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x7c, 0x0a,
	0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6a, 0x0a, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x2b, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x73,
	0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serve_proto_rawDescOnce sync.Once
	file_serve_proto_rawDescData = file_serve_proto_rawDesc
)

func file_serve_proto_rawDescGZIP() []byte {
	file_serve_proto_rawDescOnce.Do(func() {
		file_serve_proto_rawDescData = protoimpl.X.CompressGZIP(file_serve_proto_rawDescData)
	})
	return file_serve_proto_rawDescData
}

var file_serve_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_serve_proto_goTypes = []interface{}{
	(*HandleMessageRequest)(nil),  // 0: NWNX4.RPC.Proto.Serve.HandleMessageRequest
	(*Message)(nil),               // 1: NWNX4.RPC.Proto.Serve.Message
	(*SubMessage)(nil),            // 2: NWNX4.RPC.Proto.Serve.SubMessage
	(*HandleMessageResponse)(nil), // 3: NWNX4.RPC.Proto.Serve.HandleMessageResponse
	nil,                           // 4: NWNX4.RPC.Proto.Serve.Message.SubMessagesEntry
}
var file_serve_proto_depIdxs = []int32{
	1, // 0: NWNX4.RPC.Proto.Serve.HandleMessageRequest.message:type_name -> NWNX4.RPC.Proto.Serve.Message
	4, // 1: NWNX4.RPC.Proto.Serve.Message.SubMessages:type_name -> NWNX4.RPC.Proto.Serve.Message.SubMessagesEntry
	2, // 2: NWNX4.RPC.Proto.Serve.Message.SubMessagesEntry.value:type_name -> NWNX4.RPC.Proto.Serve.SubMessage
	0, // 3: NWNX4.RPC.Proto.Serve.MessageService.HandleMessage:input_type -> NWNX4.RPC.Proto.Serve.HandleMessageRequest
	3, // 4: NWNX4.RPC.Proto.Serve.MessageService.HandleMessage:output_type -> NWNX4.RPC.Proto.Serve.HandleMessageResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_serve_proto_init() }
func file_serve_proto_init() {
	if File_serve_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serve_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serve_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serve_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serve_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_serve_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SubMessage_NValue)(nil),
		(*SubMessage_FValue)(nil),
		(*SubMessage_SValue)(nil),
	}
	file_serve_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*HandleMessageResponse_NValue)(nil),
		(*HandleMessageResponse_FValue)(nil),
		(*HandleMessageResponse_SValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serve_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serve_proto_goTypes,
		DependencyIndexes: file_serve_proto_depIdxs,
		MessageInfos:      file_serve_proto_msgTypes,
	}.Build()
	File_serve_proto = out.File
	file_serve_proto_rawDesc = nil
	file_serve_proto_goTypes = nil
	file_serve_proto_depIdxs = nil
}
