// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.22.2
// source: nwnx.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NWNXGetIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SFunction string `protobuf:"bytes,1,opt,name=sFunction,proto3" json:"sFunction,omitempty"`
	SParam1   string `protobuf:"bytes,2,opt,name=sParam1,proto3" json:"sParam1,omitempty"`
	NParam2   int32  `protobuf:"varint,3,opt,name=nParam2,proto3" json:"nParam2,omitempty"`
}

func (x *NWNXGetIntRequest) Reset() {
	*x = NWNXGetIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXGetIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXGetIntRequest) ProtoMessage() {}

func (x *NWNXGetIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXGetIntRequest.ProtoReflect.Descriptor instead.
func (*NWNXGetIntRequest) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{0}
}

func (x *NWNXGetIntRequest) GetSFunction() string {
	if x != nil {
		return x.SFunction
	}
	return ""
}

func (x *NWNXGetIntRequest) GetSParam1() string {
	if x != nil {
		return x.SParam1
	}
	return ""
}

func (x *NWNXGetIntRequest) GetNParam2() int32 {
	if x != nil {
		return x.NParam2
	}
	return 0
}

type NWNXGetIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NWNXGetIntResponse) Reset() {
	*x = NWNXGetIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXGetIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXGetIntResponse) ProtoMessage() {}

func (x *NWNXGetIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXGetIntResponse.ProtoReflect.Descriptor instead.
func (*NWNXGetIntResponse) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{1}
}

func (x *NWNXGetIntResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NWNXSetIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SFunction string `protobuf:"bytes,1,opt,name=sFunction,proto3" json:"sFunction,omitempty"`
	SParam1   string `protobuf:"bytes,2,opt,name=sParam1,proto3" json:"sParam1,omitempty"`
	NParam2   int32  `protobuf:"varint,3,opt,name=nParam2,proto3" json:"nParam2,omitempty"`
	NValue    int32  `protobuf:"varint,4,opt,name=nValue,proto3" json:"nValue,omitempty"`
}

func (x *NWNXSetIntRequest) Reset() {
	*x = NWNXSetIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXSetIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXSetIntRequest) ProtoMessage() {}

func (x *NWNXSetIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXSetIntRequest.ProtoReflect.Descriptor instead.
func (*NWNXSetIntRequest) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{2}
}

func (x *NWNXSetIntRequest) GetSFunction() string {
	if x != nil {
		return x.SFunction
	}
	return ""
}

func (x *NWNXSetIntRequest) GetSParam1() string {
	if x != nil {
		return x.SParam1
	}
	return ""
}

func (x *NWNXSetIntRequest) GetNParam2() int32 {
	if x != nil {
		return x.NParam2
	}
	return 0
}

func (x *NWNXSetIntRequest) GetNValue() int32 {
	if x != nil {
		return x.NValue
	}
	return 0
}

type NWNXSetIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NWNXSetIntResponse) Reset() {
	*x = NWNXSetIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXSetIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXSetIntResponse) ProtoMessage() {}

func (x *NWNXSetIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXSetIntResponse.ProtoReflect.Descriptor instead.
func (*NWNXSetIntResponse) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{3}
}

type NWNXGetFloatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SFunction string `protobuf:"bytes,1,opt,name=sFunction,proto3" json:"sFunction,omitempty"`
	SParam1   string `protobuf:"bytes,2,opt,name=sParam1,proto3" json:"sParam1,omitempty"`
	NParam2   int32  `protobuf:"varint,3,opt,name=nParam2,proto3" json:"nParam2,omitempty"`
}

func (x *NWNXGetFloatRequest) Reset() {
	*x = NWNXGetFloatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXGetFloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXGetFloatRequest) ProtoMessage() {}

func (x *NWNXGetFloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXGetFloatRequest.ProtoReflect.Descriptor instead.
func (*NWNXGetFloatRequest) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{4}
}

func (x *NWNXGetFloatRequest) GetSFunction() string {
	if x != nil {
		return x.SFunction
	}
	return ""
}

func (x *NWNXGetFloatRequest) GetSParam1() string {
	if x != nil {
		return x.SParam1
	}
	return ""
}

func (x *NWNXGetFloatRequest) GetNParam2() int32 {
	if x != nil {
		return x.NParam2
	}
	return 0
}

type NWNXGetFloatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NWNXGetFloatResponse) Reset() {
	*x = NWNXGetFloatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXGetFloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXGetFloatResponse) ProtoMessage() {}

func (x *NWNXGetFloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXGetFloatResponse.ProtoReflect.Descriptor instead.
func (*NWNXGetFloatResponse) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{5}
}

func (x *NWNXGetFloatResponse) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type NWNXSetFloatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SFunction string  `protobuf:"bytes,1,opt,name=sFunction,proto3" json:"sFunction,omitempty"`
	SParam1   string  `protobuf:"bytes,2,opt,name=sParam1,proto3" json:"sParam1,omitempty"`
	NParam2   int32   `protobuf:"varint,3,opt,name=nParam2,proto3" json:"nParam2,omitempty"`
	FValue    float32 `protobuf:"fixed32,4,opt,name=fValue,proto3" json:"fValue,omitempty"`
}

func (x *NWNXSetFloatRequest) Reset() {
	*x = NWNXSetFloatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXSetFloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXSetFloatRequest) ProtoMessage() {}

func (x *NWNXSetFloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXSetFloatRequest.ProtoReflect.Descriptor instead.
func (*NWNXSetFloatRequest) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{6}
}

func (x *NWNXSetFloatRequest) GetSFunction() string {
	if x != nil {
		return x.SFunction
	}
	return ""
}

func (x *NWNXSetFloatRequest) GetSParam1() string {
	if x != nil {
		return x.SParam1
	}
	return ""
}

func (x *NWNXSetFloatRequest) GetNParam2() int32 {
	if x != nil {
		return x.NParam2
	}
	return 0
}

func (x *NWNXSetFloatRequest) GetFValue() float32 {
	if x != nil {
		return x.FValue
	}
	return 0
}

type NWNXSetFloatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NWNXSetFloatResponse) Reset() {
	*x = NWNXSetFloatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXSetFloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXSetFloatResponse) ProtoMessage() {}

func (x *NWNXSetFloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXSetFloatResponse.ProtoReflect.Descriptor instead.
func (*NWNXSetFloatResponse) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{7}
}

type NWNXGetStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SFunction string `protobuf:"bytes,1,opt,name=sFunction,proto3" json:"sFunction,omitempty"`
	SParam1   string `protobuf:"bytes,2,opt,name=sParam1,proto3" json:"sParam1,omitempty"`
	NParam2   int32  `protobuf:"varint,3,opt,name=nParam2,proto3" json:"nParam2,omitempty"`
}

func (x *NWNXGetStringRequest) Reset() {
	*x = NWNXGetStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXGetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXGetStringRequest) ProtoMessage() {}

func (x *NWNXGetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXGetStringRequest.ProtoReflect.Descriptor instead.
func (*NWNXGetStringRequest) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{8}
}

func (x *NWNXGetStringRequest) GetSFunction() string {
	if x != nil {
		return x.SFunction
	}
	return ""
}

func (x *NWNXGetStringRequest) GetSParam1() string {
	if x != nil {
		return x.SParam1
	}
	return ""
}

func (x *NWNXGetStringRequest) GetNParam2() int32 {
	if x != nil {
		return x.NParam2
	}
	return 0
}

type NWNXGetStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NWNXGetStringResponse) Reset() {
	*x = NWNXGetStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXGetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXGetStringResponse) ProtoMessage() {}

func (x *NWNXGetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXGetStringResponse.ProtoReflect.Descriptor instead.
func (*NWNXGetStringResponse) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{9}
}

func (x *NWNXGetStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NWNXSetStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SFunction string `protobuf:"bytes,1,opt,name=sFunction,proto3" json:"sFunction,omitempty"`
	SParam1   string `protobuf:"bytes,2,opt,name=sParam1,proto3" json:"sParam1,omitempty"`
	NParam2   int32  `protobuf:"varint,3,opt,name=nParam2,proto3" json:"nParam2,omitempty"`
	SValue    string `protobuf:"bytes,4,opt,name=sValue,proto3" json:"sValue,omitempty"`
}

func (x *NWNXSetStringRequest) Reset() {
	*x = NWNXSetStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXSetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXSetStringRequest) ProtoMessage() {}

func (x *NWNXSetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXSetStringRequest.ProtoReflect.Descriptor instead.
func (*NWNXSetStringRequest) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{10}
}

func (x *NWNXSetStringRequest) GetSFunction() string {
	if x != nil {
		return x.SFunction
	}
	return ""
}

func (x *NWNXSetStringRequest) GetSParam1() string {
	if x != nil {
		return x.SParam1
	}
	return ""
}

func (x *NWNXSetStringRequest) GetNParam2() int32 {
	if x != nil {
		return x.NParam2
	}
	return 0
}

func (x *NWNXSetStringRequest) GetSValue() string {
	if x != nil {
		return x.SValue
	}
	return ""
}

type NWNXSetStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NWNXSetStringResponse) Reset() {
	*x = NWNXSetStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nwnx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NWNXSetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NWNXSetStringResponse) ProtoMessage() {}

func (x *NWNXSetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nwnx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NWNXSetStringResponse.ProtoReflect.Descriptor instead.
func (*NWNXSetStringResponse) Descriptor() ([]byte, []int) {
	return file_nwnx_proto_rawDescGZIP(), []int{11}
}

var File_nwnx_proto protoreflect.FileDescriptor

var file_nwnx_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x77, 0x6e, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x4e, 0x57,
	0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x22, 0x65, 0x0a, 0x11, 0x4e, 0x57, 0x4e, 0x58, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x22, 0x2a,
	0x0a, 0x12, 0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7d, 0x0a, 0x11, 0x4e, 0x57,
	0x4e, 0x58, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x32, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x4e, 0x57, 0x4e,
	0x58, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x67, 0x0a, 0x13, 0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x22, 0x2c, 0x0a, 0x14, 0x4e, 0x57, 0x4e, 0x58,
	0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7f, 0x0a, 0x13, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65,
	0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x06, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4e, 0x57, 0x4e, 0x58, 0x53,
	0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x68, 0x0a, 0x14, 0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x32, 0x22, 0x2d, 0x0a, 0x15, 0x4e, 0x57, 0x4e,
	0x58, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x80, 0x01, 0x0a, 0x14, 0x4e, 0x57, 0x4e,
	0x58, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x4e,
	0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xed, 0x03, 0x0a, 0x0b, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x49,
	0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e,
	0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e,
	0x58, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x49, 0x0a, 0x0a, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x12, 0x1c, 0x2e,
	0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65,
	0x74, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x4e, 0x57,
	0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x49,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x4e, 0x57,
	0x4e, 0x58, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x1e, 0x2e, 0x4e, 0x57, 0x4e,
	0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x4e, 0x57, 0x4e,
	0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x4e,
	0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x1e, 0x2e, 0x4e, 0x57,
	0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x4e, 0x57,
	0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d,
	0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x2e,
	0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x52, 0x0a, 0x0d, 0x4e, 0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x1f, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e, 0x57,
	0x4e, 0x58, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x4e, 0x57, 0x4e, 0x58, 0x34, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x4e,
	0x57, 0x4e, 0x58, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nwnx_proto_rawDescOnce sync.Once
	file_nwnx_proto_rawDescData = file_nwnx_proto_rawDesc
)

func file_nwnx_proto_rawDescGZIP() []byte {
	file_nwnx_proto_rawDescOnce.Do(func() {
		file_nwnx_proto_rawDescData = protoimpl.X.CompressGZIP(file_nwnx_proto_rawDescData)
	})
	return file_nwnx_proto_rawDescData
}

var file_nwnx_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_nwnx_proto_goTypes = []interface{}{
	(*NWNXGetIntRequest)(nil),     // 0: NWNX4.RPC.NWNXGetIntRequest
	(*NWNXGetIntResponse)(nil),    // 1: NWNX4.RPC.NWNXGetIntResponse
	(*NWNXSetIntRequest)(nil),     // 2: NWNX4.RPC.NWNXSetIntRequest
	(*NWNXSetIntResponse)(nil),    // 3: NWNX4.RPC.NWNXSetIntResponse
	(*NWNXGetFloatRequest)(nil),   // 4: NWNX4.RPC.NWNXGetFloatRequest
	(*NWNXGetFloatResponse)(nil),  // 5: NWNX4.RPC.NWNXGetFloatResponse
	(*NWNXSetFloatRequest)(nil),   // 6: NWNX4.RPC.NWNXSetFloatRequest
	(*NWNXSetFloatResponse)(nil),  // 7: NWNX4.RPC.NWNXSetFloatResponse
	(*NWNXGetStringRequest)(nil),  // 8: NWNX4.RPC.NWNXGetStringRequest
	(*NWNXGetStringResponse)(nil), // 9: NWNX4.RPC.NWNXGetStringResponse
	(*NWNXSetStringRequest)(nil),  // 10: NWNX4.RPC.NWNXSetStringRequest
	(*NWNXSetStringResponse)(nil), // 11: NWNX4.RPC.NWNXSetStringResponse
}
var file_nwnx_proto_depIdxs = []int32{
	0,  // 0: NWNX4.RPC.NWNXService.NWNXGetInt:input_type -> NWNX4.RPC.NWNXGetIntRequest
	2,  // 1: NWNX4.RPC.NWNXService.NWNXSetInt:input_type -> NWNX4.RPC.NWNXSetIntRequest
	4,  // 2: NWNX4.RPC.NWNXService.NWNXGetFloat:input_type -> NWNX4.RPC.NWNXGetFloatRequest
	6,  // 3: NWNX4.RPC.NWNXService.NWNXSetFloat:input_type -> NWNX4.RPC.NWNXSetFloatRequest
	8,  // 4: NWNX4.RPC.NWNXService.NWNXGetString:input_type -> NWNX4.RPC.NWNXGetStringRequest
	10, // 5: NWNX4.RPC.NWNXService.NWNXSetString:input_type -> NWNX4.RPC.NWNXSetStringRequest
	1,  // 6: NWNX4.RPC.NWNXService.NWNXGetInt:output_type -> NWNX4.RPC.NWNXGetIntResponse
	3,  // 7: NWNX4.RPC.NWNXService.NWNXSetInt:output_type -> NWNX4.RPC.NWNXSetIntResponse
	5,  // 8: NWNX4.RPC.NWNXService.NWNXGetFloat:output_type -> NWNX4.RPC.NWNXGetFloatResponse
	7,  // 9: NWNX4.RPC.NWNXService.NWNXSetFloat:output_type -> NWNX4.RPC.NWNXSetFloatResponse
	9,  // 10: NWNX4.RPC.NWNXService.NWNXGetString:output_type -> NWNX4.RPC.NWNXGetStringResponse
	11, // 11: NWNX4.RPC.NWNXService.NWNXSetString:output_type -> NWNX4.RPC.NWNXSetStringResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_nwnx_proto_init() }
func file_nwnx_proto_init() {
	if File_nwnx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nwnx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXGetIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXGetIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXSetIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXSetIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXGetFloatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXGetFloatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXSetFloatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXSetFloatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXGetStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXGetStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXSetStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nwnx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NWNXSetStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nwnx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nwnx_proto_goTypes,
		DependencyIndexes: file_nwnx_proto_depIdxs,
		MessageInfos:      file_nwnx_proto_msgTypes,
	}.Build()
	File_nwnx_proto = out.File
	file_nwnx_proto_rawDesc = nil
	file_nwnx_proto_goTypes = nil
	file_nwnx_proto_depIdxs = nil
}
