name: nwnx4-plugin-rpc
on: [push, pull_request]

jobs:
  build:
    name: Build NWNX4 plugin xp_rpc
    runs-on: windows-latest  # Change the operating system to Windows
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install MinGW-w64 32-bit
        with:
          msystem: MINGW32
          update: true
          install: mingw-w64-i686-toolchain

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Win32 x86 DLL for NWNX4
        shell: powershell
        env:
          GOOS: windows
          GOARCH: 386
          CGO_ENABLED: 1
        working-directory: plugin
        run: go build -ldflags '-s -w -linkmode external -extldflags -static-libgcc -extldflags -static-libstdc++' -o ../dist/xp_rpc.dll -buildmode=c-shared

      - name: Copy all necessary files into distribution
        shell: powershell
        run: |
          Copy-Item -Recurse -Path .\include -Destination .\dist
          Copy-Item -Recurse -Path .\proto -Destination .\dist
          Copy-Item -Path .\plugin\xp_rpc.yml -Destination .\dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xp_rpc-${{ github.sha }}
          path: dist/

  release:
    name: Create release if tagged
    needs: build
    if: ${{startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: xp_rpc-${{github.sha}}
          path: dist/

      - name: Compress release
        working-directory: dist
        run: |
          zip -r ../xp_rpc.zip *

      - name: Extract release info
        shell: bash
        id: rel_info
        run: |
          TAG=$(echo '${{ github.ref }}' | grep -oE '\bv[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$' || true)
          echo "::set-output name=tag::$TAG"

          [[ "$TAG" =~ -rc[0-9]+$ ]] && PRERELEASE=true || PRERELEASE=false
          echo "::set-output name=prerelease::$PRERELEASE"

          if [[ "$TAG" != "" ]]; then
            echo "Deploying $TAG (prerelease=$PRERELEASE)"
          else
            echo "Not a tagged release"
          fi

      - name: Create draft release with artifact
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.rel_info.outputs.tag }}
          prerelease: ${{ steps.rel_info.outputs.prerelease }}
          files: xp_rpc.zip
          draft: true