name: NWNX4-plugins-xp_rpc
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      # Install go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18rc1

      # Install base requirements
      - name: Install Go requirements
        shell: 'bash'
        run: |
          go get -v -t -d ./src

      # Build Win32 DLL
      - name: Build Win32 x86 DLL for NWNX4
        env:
          GOOS: windows
          GOARCH: 386
          CGO_ENABLED: 1
        shell: bash
        run: |
          go build -ldflags '-s -w' -o dist/xp_rpc.dll -buildmode=c-shared src/lib.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/
          name: xp_rpc-${{github.sha}}

  release:
    name: Create release if tagged
    if: ${{startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: xp_rpc-${{ github.sha }}
          path: nwnx4/plugins/

      - name: Compress release
        run: |
          zip -r xp_rpc.zip nwnx4/plugins/

      - name: Extract release info
        shell: bash
        id: rel_info
        run: |
          TAG=$(echo '${{ github.ref }}' | grep -oE '\bv[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$' || true)
          echo "::set-output name=tag::$TAG"

          [[ "$TAG" =~ -rc[0-9]+$ ]] && PRERELEASE=true || PRERELEASE=false
          echo "::set-output name=prerelease::$PRERELEASE"

          if [[ "$TAG" != "" ]]; then
            echo "Deploying $TAG (prerelease=$PRERELEASE)"
          else
            echo "Not a tagged release"
          fi

      - name: Create draft release with artifact
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.rel_info.outputs.tag }}
          prerelease: ${{ steps.rel_info.outputs.prerelease }}
          files: xp_rpc.zip
          draft: true