name: NWNX4-plugins-xp_rpc
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y gcc-multilib
          sudo apt-get install -y gcc-mingw-w64

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-rc1
          stable: false

      - name: Build Win32 x86 DLL for NWNX4
        shell: bash
        env:
          GOOS: windows
          GOARCH: 386
          CGO_ENABLED: 1
          CC: i686-w64-mingw32-gcc
          CXX: i686-w64-mingw32-g++
        working-directory: xp_rpc
        run: go build -ldflags '-s -w' -o ../dist/xp_rpc.dll -buildmode=c-shared main.go

      - name: Copy Protobufs into package
        shell: bash
        run: |
          cp -r ./proto ./dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/
          name: xp_rpc-${{github.sha}}

  release:
    name: Create release if tagged
    if: ${{startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: xp_rpc-${{ github.sha }}
          path: nwnx4/plugins/

      - name: Compress release
        run: |
          zip -r xp_rpc.zip nwnx4/plugins/

      - name: Extract release info
        shell: bash
        id: rel_info
        run: |
          TAG=$(echo '${{ github.ref }}' | grep -oE '\bv[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$' || true)
          echo "::set-output name=tag::$TAG"

          [[ "$TAG" =~ -rc[0-9]+$ ]] && PRERELEASE=true || PRERELEASE=false
          echo "::set-output name=prerelease::$PRERELEASE"

          if [[ "$TAG" != "" ]]; then
            echo "Deploying $TAG (prerelease=$PRERELEASE)"
          else
            echo "Not a tagged release"
          fi

      - name: Create draft release with artifact
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.rel_info.outputs.tag }}
          prerelease: ${{ steps.rel_info.outputs.prerelease }}
          files: xp_rpc.zip
          draft: true